# Generated by Django 2.1.5 on 2020-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200318_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
