# Generated by Django 2.1.5 on 2020-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200318_1950'),
        ('main', '0004_auto_20200318_1922'),
    ]

    operations = [
    ]
