# Generated by Django 2.1.5 on 2020-03-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200312_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='question',
            new_name='post',
        ),
    ]
