# Generated by Django 2.1.5 on 2020-03-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
