# Generated by Django 2.1.5 on 2020-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
