# Generated by Django 2.1.5 on 2020-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200315_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Tell us a little about yourself....', max_length=512),
        ),
    ]
