# Generated by Django 2.1.5 on 2020-03-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200317_1541'),
        ('main', '0017_auto_20200317_1831'),
    ]

    operations = [
    ]
