# Generated by Django 2.1.5 on 2020-03-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200317_1235'),
        ('main', '0018_merge_20200317_2002'),
    ]

    operations = [
    ]
