# Generated by Django 2.1.5 on 2020-03-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200317_1723'),
        ('main', '0019_merge_20200317_2015'),
    ]

    operations = [
    ]
